### ISSUE TITLE
Y Values over 99 show ellipses

### ISSUE THREAD

**Issue by zoomies** [zemirco/swift-linechart#16]
Not sure if this is a problem, or if I missed something.  But if I try to display data that is greater than 99 then there does not seem to be enough room on the axis to show it.  I will have Y values that will be over 10,000.  Any suggestions?

**Comment by zoomies** [comment]
So, I played with the y-axis inset, and here is what I am seeing with lineChart.y.axis.inset = 35.0

![image](https://cloud.githubusercontent.com/assets/11728311/6909419/ea192d3a-d713-11e4-8e35-3047b56fcc5f.png)

**Comment by sureshkw** [comment]
This could be of help https://github.com/zemirco/swift-linechart/issues/14

**Comment by zoomies** [comment]
Thanks sureshkw - that did give me some insight.  That, along with changing the x.axis.inset which moved the y-axis line to the right so that it no longer bisects the y-axis labels.
