### ISSUE TITLE
colors array not initialized when using nib/storyboard

### ISSUE THREAD

**Issue by swift-js** [zemirco/swift-linechart#8]
When using nib or storyboard to create custom view with class 'LineChart', then only "init(coder aDecoder: NSCoder)" is called, not "init(frame: CGRect)". This means the initialization code for "self.colors" is never called and app will crash during "drawLine" at "layer.strokeColor = colors[lineIndex].CGColor"

**Comment by 07cs07** [comment]
Below code will fix the issue, initialising the colour in override function of awakeFromNib 
`    override func awakeFromNib() {
        super.awakeFromNib()
        self.backgroundColor = UIColor.clearColor()
        self.colors = [
            UIColorFromHex(0x1f77b4),
            UIColorFromHex(0xff7f0e),
            UIColorFromHex(0x2ca02c),
            UIColorFromHex(0xd62728),
            UIColorFromHex(0x9467bd),
            UIColorFromHex(0x8c564b),
            UIColorFromHex(0xe377c2),
            UIColorFromHex(0x7f7f7f),
            UIColorFromHex(0xbcbd22),
            UIColorFromHex(0x17becf)
        ]
    }`
